### ISSUE TITLE
Requirements installation error

### ISSUE THREAD

**Issue by pilarpe4** [opendatalabcz/parking-spot-detection#8]
Hi, I am trying to run your project in PyCharm, but i have an issue with the requirements. I get an Error when installing `pip install keras-retinanet==0.5.1` and some other packages.

I tried it on Windows first (same error) and decided to use Ubuntu, hoping that it will magically disappear, but it is same result. 
Help me pls!

Error:
[error.txt](https://github.com/opendatalabcz/parking-spot-detection/files/4875468/error.txt)

Screenshot of IDE:
![Screenshot from 2020-07-05 21-46-32](https://user-images.githubusercontent.com/23452555/86540963-1cfa5480-bf09-11ea-9b75-5192cba2306d.png)

**Comment by grohj** [comment]
Hi Petr,

what I can tell from the screenshot you have this (https://github.com/ayushjain1144/Aerial-Object-Detection) project cloned.  Might this be just a confusion of a repo?

Otherwise it looks like you don't have development header files for Python installed. Also this https://github.com/fizyr/keras-retinanet/issues/1082 might help you.

**Comment by pilarpe4** [comment]
Thanks for a quick reply. You are right, I am so sorry i missclicked github tab in the heat of problem solving 😅
